Repository youngeek-0410/SekigaeService, pull requests merged in 2021-08, with the labels that each got.

#37 Reactが動くようにした
  django/config/settings/base.py
  django/config/urls.py
  django/sample/__init__.py
  django/sample/admin.py
  django/sample/apps.py
  django/sample/migrations/__init__.py
  django/sample/models.py
  django/sample/tests.py
  django/sample/urls.py
  django/sample/views.py
  django/templates/base.html
  django/templates/sample/base_sample.html
  django/templates/sample/index.html
  docker-compose.yml
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/HelloWorld.tsx
  frontend/src/app.tsx
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: task:frontend, 1.priority:高

#97 add note to PR template #87
  .github/pull_request_template.md
Labels: type:enhancement

#100 install less command in container based ubuntu #95
  django/Dockerfile
  frontend/Dockerfile
Labels: type:enhancement, task:infrastructure

#139 fix typescript errors #75
  frontend/.babelrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app.tsx
  frontend/src/components/atom/askButton.tsx
  frontend/src/components/atom/startButton.tsx
  frontend/src/components/organism/menuBar.tsx
  frontend/src/pages/sekigae.tsx
  frontend/tsconfig.json
  frontend/types/images.d.ts
Labels: type:enhancement, task:frontend, 2.priority:中

#94 fix: add eslint, prettier, stylelint settings #93
  .eslintignore
  .eslintrc.js
  .prettierignore
  .prettierrc
  .stylelintrc
  package-lock.json
  package.json
  tsconfig.json
Labels: type:bug

#165 add repository field #164
  frontend/package.json
Labels: type:enhancement

#166 set the basic fonts #152
  django/static/style.css
Labels: type:enhancement, task:frontend, task:design
