Repository youngeek-0410/SekigaeService, pull requests merged in 2021-07, with the labels that each got.

#6 Create pull_request_template.md
  .github/pull_request_template.md
Labels: feature

#9 Issueテンプレートの名前と中身を修正
  .github/ISSUE_TEMPLATE/BUG_FIX.md
  .github/ISSUE_TEMPLATE/FEATURE.md
Labels: enhancement

#10 update README.md
  README.md
Labels: enhancement

#29 add common templates/ and base.html #28
  django/templates/account/base_account.html
  django/templates/base.html
Labels: task:backend, task:frontend
